name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get Version from Tag
        id: get-version
        shell: bash
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Publish Application
        run: dotnet publish .\upd8\upd8.csproj -c Release -o publish -r win-x64 --self-contained true

      - name: Create Velopack Release
        shell: bash
        run: |
          dotnet tool install -g vpk
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
          vpk pack --packId upd8 --packVersion ${{ steps.get-version.outputs.version }} --packDir publish --mainExe upd8.exe
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "upd8 ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --token ${{ secrets.GITHUB_TOKEN }}
